site_name: vNerd Docs
site_url: https://www.docs.vnerd.nl/
site_author: Karam Ajaj

repo_url: https://github.com/karam-ajaj/vnerd-docs
repo_name: karam-ajaj/vnerd-docs
# edit_uri: edit/master/docs/

# nav:
#   - Blog:
#     - blog/index.md

# nav:
#   - Home: '../'
#   - User Guide: 'hardware/hardware/index.md'
#   - Infrastructure Guide: 'Infrastructure/'

# Theme Configuration
theme:
  name: 'material'
  logo: assets/logos/vnerd-logo-white.png
  custom_dir: overrides
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # - primary: black
    # - accent: indigo
    # primary: indigo
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      # scheme: default
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.expand
    # - navigation.prune
    - navigation.path
    - navigation.top
    # - navigation.indexes
    - header.autohide
    - toc.follow
    # - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    # - navigation.footer
    - content.code.copy
    - content.code.select
    - content.action.view
    # - content.action.edit
  # static_templates:
  #   - get
plugins:
  - blog:
      # blog_dir: blog
      # blog_toc: true
      # post_dir: blog/posts
      archive: false
  - search
  - external-markdown
  - awesome-pages
  #- mkdocs-blogging-plugin
  #- fontawesome-markdown
  # - projects
  # - optimize
  # - offline
  # - charts
  # - pdf-export
  # - print-site
  - termynal:
      title: bash
      buttons: macos
      prompt_literal_start:
        - "$"
  

  # https://github.com/squidfunk/mkdocs-material/discussions/3458
  # - redirects:
  #   redirect_maps:
  #     get: https://github.com/karam-ajaj/portainer-compose/blob/main/README.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # - pymdownx.snippets:
  #     auto_append:
  #       - includes/abbreviations.md
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/karam-ajaj/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/karam.ajaj/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/karam-ajaj/
    # - icon: fontawesome/brands/slack
    #   link:
    - icon: fontawesome/brands/discord
      link: https://discordapp.com/users/1001115113245388831

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; Karam Ajaj